version: "3.1"

services:
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
    ports:
      - "27017:27017"
    networks:
      - restReactor

  mongo-experss:
    image: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXP_USERNAME:-user}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXP_PASSWORD:-password}
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:-password}
    ports:
      - "8082:8081"
    networks:
      - restReactor
    depends_on:
      - mongo-db
networks:
  restReactor:
    driver: bridge
